version: '3.6'
### get network
### ifconfig -l | xargs -n1 ipconfig getifaddr
networks:
  app-tier:
    driver: bridge
    
services: 
    db:
        image: mysql
        platform: linux/amd64 ## For Apple M1 Chip, other platoform please remove this line
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        expose:
          - "3306"
        environment: 
            MYSQL_HOST : db4free.net
            MYSQL_ROOT_PASSWORD: Shivani@19
            MYSQL_DATABASE: expense_tracker
            MYSQL_USER: asnhkiivta
            MYSQL_PASSWORD: Shivani@19
        ports:
          - "3306:3306"    
        networks:
          - app-tier      
    
        volumes: 
            - ./init:/docker-entrypoint-initdb.d

    # adminer:
    #     image: adminer
    #     restart: always
    #     ports: 
    #         - 8080:8080
    
      # phpmyadmin
        # phpmyadmin:
        #   # depends_on:
        #   #  - db
        #   image: phpmyadmin
        #   restart: always
        #   # ports:
        #   #   - "8090:80"
        #   environment:
        #     PMA_HOST: db4free.net
        #     MYSQL_ROOT_PASSWORD: Shivani@19
        #     PMA_USER: asnhkiivta
        #   networks:
        #     - mysql-phpmyadmin
