version: '3.8'
services:
	express-file-manager:
		image: ghcr.io/entespotify/express-file-manager:main
		environment:
			- BASE_DIR=/app
		ports:
			- "4000:4000"
		volumes:
			- /opt/file-manager:/app
